// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')


const { describe, it, beforeEach, afterEach } = require('mocha')
describe('multip', function () {
  this.timeout(30000)
  let driver
  let vars

  beforeEach(async function () {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function () {
    await driver.quit();
  })
  it('multip', async function () {
    await driver.get("https://safatelli.github.io/tp-test-logiciel/assets/calc.html")
    await driver.manage().window().setRect({ width: 1534, height: 605 })
    await driver.findElement(By.id("num1")).click()
    await driver.findElement(By.id("num1")).sendKeys("12")
    await driver.findElement(By.id("operator")).click()
    {
      const dropdown = await driver.findElement(By.id("operator"))
      await dropdown.findElement(By.xpath("//option[. = '*']")).click()
    }
    await driver.findElement(By.id("num2")).click()
    await driver.findElement(By.id("num2")).sendKeys("-2")
    await driver.findElement(By.css("button")).click()
    assert.equal(await driver.findElement(By.id("result")).getText(), "Résultat : -24")
  })
})
