// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')


const { describe, it, beforeEach, afterEach } = require('mocha')
describe('8. Explorez les pages supplémentaires telles que la page d\'accueil, la page "À propos", etc.', function () {
  this.timeout(30000)
  let driver
  let vars

  beforeEach(async function () {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function () {
    await driver.quit();
  })
  it('8. Explorez les pages supplémentaires telles que la page d\'accueil, la page "À propos", etc.', async function () {
    await driver.get("https://www.demoblaze.com/")
    await driver.manage().window().setRect({ width: 1552, height: 832 })
    await driver.findElement(By.css(".active > .nav-link")).click()
    assert.equal(await driver.findElement(By.id("cat")).getText(), "CATEGORIES")
    await driver.findElement(By.linkText("Contact")).click()
    await driver.findElement(By.css("#exampleModal .modal-header")).click()
    assert.equal(await driver.findElement(By.id("exampleModalLabel")).getText(), "New message")
    await driver.findElement(By.css("#exampleModal span")).click()
    await driver.findElement(By.linkText("About us")).click()
    assert.equal(await driver.findElement(By.id("videoModalLabel")).getText(), "About us")
    await driver.findElement(By.css("#videoModal .modal-header span")).click()
    await driver.findElement(By.id("cartur")).click()
    await driver.findElement(By.id("login2")).click()
    await driver.findElement(By.css("#logInModal span")).click()
    assert.equal(await driver.findElement(By.id("logInModalLabel")).getText(), "Log in")
    await driver.findElement(By.id("signin2")).click()
    await driver.findElement(By.css("#signInModal span")).click()
    assert.equal(await driver.findElement(By.id("signInModalLabel")).getText(), "Sign up")
    await driver.findElement(By.css(".active > .nav-link")).click()
    assert.equal(await driver.findElement(By.id("cat")).getText(), "CATEGORIES")
  })
})
