// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')


const { describe, it, beforeEach, afterEach } = require('mocha')
describe('Ajoutez un produit au panier.', function () {
  this.timeout(30000)
  let driver
  let vars

  beforeEach(async function () {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function () {
    await driver.quit();
  })
  it('Ajoutez un produit au panier.', async function () {
    await driver.get("https://www.demoblaze.com/")
    await driver.manage().window().setRect({ width: 1552, height: 832 })
    await driver.findElement(By.linkText("Samsung galaxy s6")).click()
    await driver.findElement(By.linkText("Add to cart")).click()
    assert(await driver.switchTo().alert().getText() == "Product added")
    await driver.findElement(By.id("cartur")).click()
    await driver.findElement(By.css("td:nth-child(2)")).click()
    assert.equal(await driver.findElement(By.css("td:nth-child(2)")).getText(), "Samsung galaxy s6")
  })
})
