# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAjoutezunproduitaupanier():
  def setup_method(self, method):
    print("Setting up the test")
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    print("Tearing down the test")
    self.driver.quit()
  
  def test_ajoutezunproduitaupanier(self):
    print("Navigating to the test page")
    self.driver.get("https://www.demoblaze.com/")
    self.driver.set_window_size(1552, 832)
    
    print("Adding 'Samsung galaxy s6' to the cart")
    self.driver.find_element(By.LINK_TEXT, "Samsung galaxy s6").click()
    self.driver.find_element(By.LINK_TEXT, "Add to cart").click()
    assert self.driver.switch_to.alert.text == "Product added"
    
    print("Navigating to the cart and checking the product")
    self.driver.find_element(By.ID, "cartur").click()
    self.driver.find_element(By.CSS_SELECTOR, "td:nth-child(2)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "td:nth-child(2)").text == "Samsung galaxy s6"
    print("Test completed successfully")

# Running the test
print("Starting the test")
TestAjoutezunproduitaupanier().test_ajoutezunproduitaupanier()
print("Test execution finished")