# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAccdezaupaniervrifiezlesarticlesajoutsetsupprimezensincessaire():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_accdezaupaniervrifiezlesarticlesajoutsetsupprimezensincessaire(self):
    self.driver.get("https://www.demoblaze.com/")
    self.driver.set_window_size(1552, 832)
    self.driver.find_element(By.LINK_TEXT, "Nokia lumia 1520").click()
    self.driver.find_element(By.LINK_TEXT, "Add to cart").click()
    assert self.driver.switch_to.alert.text == "Product added"
    self.driver.find_element(By.ID, "cartur").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "td:nth-child(2)").text == "Nokia lumia 1520"
    self.driver.find_element(By.LINK_TEXT, "Delete").click()
  
