// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

const { describe, it, beforeEach, afterEach } = require('mocha')

describe('use variables', function () {
  this.timeout(30000)
  let driver
  let vars

  beforeEach(async function () {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function () {
    await driver.quit();
  })
  it('use variables', async function () {
    vars["FakeName"] = "this is a name"
    vars["FakeAdd"] = "this is an address"
    vars["FakeCity"] = "this is a city"
    await driver.get("https://www.demoblaze.com/")
    await driver.manage().window().setRect({ width: 1051, height: 797 })
    await driver.findElement(By.linkText("Samsung galaxy s6")).click()
    await driver.findElement(By.linkText("Add to cart")).click()
    assert(await driver.switchTo().alert().getText() == "Product added")
    await driver.findElement(By.id("cartur")).click()
    await driver.findElement(By.css(".btn-success")).click()
    await driver.findElement(By.id("name")).click()
    await driver.findElement(By.id("name")).click()
    await driver.findElement(By.id("name")).sendKeys(vars["FakeName"])
    await driver.findElement(By.id("country")).sendKeys(vars["FakeAdd"])
    await driver.findElement(By.id("city")).sendKeys(vars["FakeCity"])
    await driver.findElement(By.id("card")).sendKeys(vars["FakeName"])
    await driver.findElement(By.id("month")).sendKeys("8")
    await driver.findElement(By.id("year")).sendKeys("2004")
    await driver.findElement(By.css("#orderModal .btn-primary")).click()
    await driver.findElement(By.css(".form-group:nth-child(6)")).click()
    await driver.findElement(By.css("#orderModal .btn-primary")).click()
    await driver.findElement(By.css("h2:nth-child(6)")).click()
    assert.equal(await driver.findElement(By.css("h2:nth-child(6)")).getText(), "Thank you for your purchase!")
  })
})
